---
- block:

  - name: download source
    unarchive:
      creates: "/opt/redis-{{ redis_version }}/Makefile"
      src: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
      dest: /opt
      copy: no
    tags:
    - redis
    
  - name: make install
    command: make -j{{ ansible_processor_cores }} install
    args:
      chdir: "/opt/redis-{{ redis_version }}"
      creates: "/usr/local/bin/redis-server"
    notify:
    - restart redis
    tags:
    - redis

  - name: create redis user
    user:
      name: redis
      system: yes
      shell: /bin/false
    sudo: yes
    tags:
    - redis

  - name: create redis directories
    file:
      path: "{{ item }}"
      state: directory
      owner: redis
    with_items:
    - "{{ redis_lib_dir }}"
    - "{{ redis_etc_dir }}"
    notify:
    - restart redis
    tags:
    - redis

  # TODO consider use validate=... to stop the service before modifying
  - name: redis config
    template:
      src: "templates/redis.conf"
      dest: "{{ redis_etc_dir }}/redis.conf"
      owner: redis
      group: redis
      mode: 0644
    notify:
    - restart redis
    tags:
    - redis

  - name: redis service
    template:
      src: "templates/redis.service"
      dest: "/etc/systemd/system/redis.service"
    register: redis_service
    notify:
    - restart redis
    tags:
    - redis

  - name: redis service -> systemctl daemon-reload
    shell: systemctl daemon-reload
    when: redis_service.changed
    notify:
    - restart redis
    tags:
    - redis

  - name: redis enable
    service:
      name: redis
      enabled: yes
    tags:
    - redis

  become: yes
