---

- name: add groups
  become: true
  group:
    name: "{{ item }}"
    state: present
  with_items:
  - trading
  - algo
  tags:
  - infra

- name: add users
  become: true
  user:
    name: "{{ item }}"
    system: yes
    group: "{{ item }}"
  with_items:
  - trading
  - algo
  tags:
  - infra

- name: adding users to group trading
  become: true
  user:
    name: "{{ item }}"
    groups: trading
    append: yes
  with_items:
  - trading
  - "{{ ansible_user }}"
  tags:
  - infra

- name: create directories for trading
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: trading
    group: trading
    mode: 0770
  with_items:
  - /trading
  - /trading/config
  - /trading/bin
  - /trading/run
  - /trading/logs
  - /trading/infra
  - /trading/data
  tags:
  - infra

- name: create directories for algo
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: algo
    group: algo
    mode: 0770
  with_items:
  - /algo
  - /algo/config
  - /algo/bin
  - /algo/logs
  tags:
  - infra

- name: create directories for conda
  become: true
  become_user: trading
  file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx,g+s
  with_items:
  - /home/trading/.conda
  - /home/trading/.conda/pkgs
  tags:
  - infra

- name: create files for conda
  become: true
  become_user: trading
  file:
    path: /home/trading/.conda/environments.txt
    state: touch
    mode: "u=rw,g=rw,o=r"
  tags:
  - infra

- name: create conda3 environment
  become: true
  become_user: trading
  shell: "/usr/local/bin/Miniconda3-latest-Linux-x86_64.sh -b -p /trading/infra/miniconda3"
  args:
    creates: "/trading/infra/miniconda3"
  tags:
  - infra

- name: create .condarc in the conda3 environment
  become: true
  become_user: trading
  template:
    src: "templates/condarc"
    dest: "/trading/infra/miniconda3/.condarc"
    mode: 0644
  tags:
  - infra

- name: update conda3 to latest
  become: true
  become_user: trading
  shell: "/trading/infra/miniconda3/bin/conda update -n root conda"
  tags:
  - infra
