---

- name: add groups
  become: true
  group:
    name: "{{ item }}"
    state: present
  with_items:
  - trading
  - algo
  tags:
  - infra

- name: add users
  become: true
  user:
    name: "{{ item }}"
    system: yes
    group: "{{ item }}"
  with_items:
  - trading
  - algo
  tags:
  - infra

- name: adding users to group trading
  become: true
  user:
    name: "{{ item }}"
    groups: trading
    append: yes
  with_items:
  - trading
  - "{{ ansible_user }}"
  tags:
  - infra

- name: create directories for trading
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: trading
    group: trading
    mode: 0750
  with_items:
  - /trading
  - /trading/config
  - /trading/bin
  - /trading/run
  - /trading/logs
  - /trading/infra
  - /trading/data
  tags:
  - infra

- name: create directories for algo
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: algo
    group: algo
    mode: 0750
  with_items:
  - /algo
  - /algo/config
  - /algo/bin
  - /algo/logs
  tags:
  - infra

# FIXME(thraneh): this will fail if ansible_user has just been added to the trading group... unsure how to refresh
- name: create conda3 environment
  shell: /usr/local/bin/Miniconda3-latest-Linux-x86_64.sh -b -p /trading/infra/miniconda3
  args:
    creates: "/trading/infra/miniconda3"
  tags:
  - infra
  - hans

- name: set miniconda3 ownership
  become: true
  file:
    path: "/trading/infra/miniconda3"
    owner: trading
    group: trading
    mode: "g+w"
    recurse: yes
  tags:
  - infra

- name: create .condarc in the conda3 environment
  become: true
  template:
    src: "templates/condarc"
    dest: "/trading/infra/miniconda3/.condarc"
    owner: trading
    group: trading
    mode: 0644
  tags:
  - infra

- name: update conda3 to latest
  shell: /trading/infra/miniconda3/bin/conda update -n root conda
  tags:
  - infra

- name: set miniconda3 ownership
  become: true
  file:
    path: "/trading/infra/miniconda3"
    owner: trading
    group: trading
    mode: "g+w"
    recurse: yes
  tags:
  - infra
