---

# TODO(thraneh): change to ansible user

- hosts: all
  remote_user: root
  become_user: root
  roles:
  - baseline
  - sysadmin
  - conda

- hosts: trading
  remote_user: root
  become_user: root
  roles:
  - infra
  - prometheus
  - nginx
  - redis

- hosts: development
  remote_user: root
  become_user: root
  roles:
  - devtools
