---

- block:

  - name: create conda environment file
    template:
      src: "templates/conda-environment.yml"
      dest: "/trading/infra/conda-environment.yml"
      owner: trading
      group: trading
      mode: 0640
    tags:
    - quinclas

  - name: update conda
    shell: /trading/infra/miniconda3/bin/conda update -n base conda
    become_user: trading
    tags:
    - quinclas

  - name: test existence of the quinclas conda environment
    shell: /trading/infra/miniconda3/bin/conda env list | grep "^quinclas "
    register: conda_quinclas
    failed_when: ( conda_quinclas.rc not in [ 0, 1 ] )
    become_user: trading
    tags:
    - quinclas

  - name: create the quinclas conda environment
    shell: /trading/infra/miniconda3/bin/conda env create -f /trading/infra/conda-environment.yml
    when: conda_quinclas.rc == 1
    become_user: trading
    tags:
    - quinclas

  - name: create daemon control scripts for gateways
    template:
      src: "templates/quinclas-gateway.sh"
      dest: "/trading/bin/quinclas-{{ item }}.sh"
      owner: trading
      group: trading
      mode: 0750
    with_items:
      - "{{ gateways }}"
    tags:
    - quinclas

  - name: create run directories for gateways
    file:
      path: "/trading/run/{{ item }}"
      state: directory
      owner: trading
      group: trading
      mode: 0750
    with_items:
      - "{{ gateways }}"
    tags:
    - quinclas

# TODO: change user to trading
# TODO: time-zones ???

  - name: create crontab entries for starting gateways
    cron:
      name: "quinclas-{{ item }}-start"
      weekday: "1-5"
      hour: 9
      minute: 14
      job: "/trading/bin/quinclas-{{ item }}.sh --start >/dev/null 2>&1"
      user: trading
    with_items:
      - "{{ gateways }}"
    tags:
    - quinclas

  - name: create crontab entries for stopping gateway
    cron:
      name: "quinclas-{{ item }}-stop"
      weekday: "1-5"
      hour: 15
      minute: 16
      job: "/trading/bin/quinclas-{{ item }}.sh --stop >/dev/null 2>&1"
      user: trading
    with_items:
      - "{{ gateways }}"
    tags:
    - quinclas

  - name: create daemon control script for collector
    template:
      src: "templates/example-collector.sh"
      dest: "/trading/bin/example-collector.sh"
      owner: trading
      group: trading
      mode: 0750
    tags:
    - quinclas

  - name: create run directory for collector
    file:
      path: "/trading/run/collector"
      state: directory
      owner: trading
      group: trading
      mode: 0750
    tags:
    - quinclas

  - name: create crontab entry for starting collector
    cron:
      name: "example-collector-start"
      weekday: "1-5"
      hour: 9
      minute: 14
      job: "/trading/bin/example-collector.sh --start >/dev/null 2>&1"
      user: trading
    tags:
    - quinclas

  - name: create crontab entry for stopping collector
    cron:
      name: "example-collector-stop"
      weekday: "1-5"
      hour: 15
      minute: 16
      job: "/trading/bin/example-collector.sh --stop >/dev/null 2>&1"
      user: trading
    tags:
    - quinclas

  become: true
