global:
  scrape_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: ['localhost:19999']

{% for gateway in gateways %}
  - job_name: 'roq-{{ gateway }}'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:{{ gateway_ports[gateway] }}']
{% endfor %}
