---

###################
### TIMEDATECTL ###
###################

- name: test ntp
  shell: bash -c '/usr/bin/timedatectl status | grep "Network time on. yes" > /dev/null'
  register: timedatectl_ntp
  changed_when: timedatectl_ntp.rc == 1
  failed_when: timedatectl_ntp.rc > 1
  tags:
  - sysadmin
  - timedatectl

- name: enable ntp
  become: true
  command: /usr/bin/timedatectl set-ntp true
  when: timedatectl_ntp.rc != 0
  tags:
  - sysadmin
  - timedatectl

###############
### SYSSTAT ###
###############

- name: install tools (debian)
  become: true
  apt:
    name: sysstat
    state: present
  when: ansible_os_family == "Debian"
  tags:
  - sysadmin
  - sysstat

- name: install tools (redhat)
  become: true
  yum:
    name: sysstat
    state: present
  when: ansible_os_family == "RedHat"
  tags:
  - sysadmin
  - sysstat

- name: enable sysstat (debian)
  become: true
  replace:
    dest: '/etc/default/sysstat' 
    regexp: 'ENABLED="false"'
    replace: 'ENABLED="true"'
  when: ansible_os_family == "Debian"
  notify:
    - restart sysstat
  tags:
  - sysadmin
  - sysstat

#############
### TOOLS ###
#############

- name: install tools (debian)
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - iotop
    - iftop
    - nethogs
    - dstat
    - lsof
    - wget
    - curl
    - vim
    - bash-completion
    - mailutils  ###
    - traceroute
    - whois
    - daemon  ###
    - zip
    - unzip
  when: ansible_os_family == "Debian"
  tags:
  - sysadmin
  - tools

- name: install tools (redhat)
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - iotop
    - iftop
    - nethogs
    - dstat
    - lsof
    - wget
    - curl
    - vim
    - bash-completion
    - mailx  ###
    - traceroute
    - whois
    - zip
    - unzip
  when: ansible_os_family == "RedHat"
  tags:
  - sysadmin
  - tools

- name: install libslack (redhat)
  become: true
  yum:
    name: http://libslack.org/download/libslack-0.6-1.x86_64.rpm
    state: present
  when: ansible_os_family == "RedHat"
  tags:
  - sysadmin
  - tools

############
### BASH ###
############

- name: bash profile -- default editor + avoid history leaks
  become: true
  template:
    src: "templates/profile.sh"
    dest: "/etc/profile.d/00-aliases.sh"
    owner: root
    mode: 0644
  tags:
  - sysadmin
  - bash

###########################
### UNATTENDED-UPGRADES ###
###########################

- name: unattended-upgrades (debian)
  apt:
    name: unattended-upgrades
    state: present
  when: ansible_os_family == "Debian"
  tags:
  - sysadmin
