---

- name: pull docker images
  become: true
  docker_image:
    name: "{{ item }}"
    http_timeout: 300
  environment: "{{proxy_env | default({})}}"
  with_items:
    - "consul"
    - "vault"
  tags:
  - hashicorp
