---
- name: restart prometheus
  become: true
  service: name=prometheus state=restarted enabled=yes
- name: restart node-exporter
  become: true
  service: name=node-exporter state=restarted enabled=yes
- name: restart alertmanager
  become: true
  service: name=alertmanager state=restarted enabled=yes
