---

- name: update and upgrade packages (debian)
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400  # 24 hours
  when: ansible_os_family == "Debian"
  tags:
  - baseline

- name: update and upgrade packages (redhat)
  become: true
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"
  tags:
  - baseline

- name: install epel-release (redhat)
  become: true
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"
  tags:
  - baseline
