---

##############
### DOCKER ###
##############

- name: docker pull images
  become: true
  docker_image:
    name: "{{ item }}"
    http_timeout: 300
  environment: "{{proxy_env | default({})}}"
  with_items:
    - "roqtrading/roq-femasapi"
    - "roqtrading/roq-samples"
  tags:
  - roq-trading

#############
### CONDA ###
#############

- name: create conda environment file
  become: true
  template:
    src: "templates/conda-environment.yml"
    dest: "/trading/infra/conda-environment.yml"
    owner: trading
    group: trading
    mode: 0640
  tags:
  - roq-trading

- name: test existence of the roq conda environment
  become: true
  become_user: trading
  shell: /trading/infra/miniconda3/bin/conda env list | grep "^roq "
  register: conda_roq
  failed_when: ( conda_roq.rc not in [ 0, 1 ] )
  tags:
  - roq-trading

- name: create the roq conda environment
  become: true
  become_user: trading
  shell: /trading/infra/miniconda3/bin/conda env create -f /trading/infra/conda-environment.yml
  when: conda_roq.rc == 1
  tags:
  - roq-trading

################
### GATEWAYS ###
################

# https://unix.stackexchange.com/questions/265704/start-stop-a-systemd-service-at-specific-times

- name: create config directory per gateway
  become: true
  file:
    dest: "/trading/config/{{ item }}"
    state: directory
    owner: trading
    group: trading
    mode: 0750
  with_items:
    - "femasapi"
  tags:
  - roq-trading

# TODO(thraneh): rename config files and loop over gateways?
- name: create config files
  become: true
  template:
    src: "templates/femasapi-{{ item }}"
    dest: "/trading/config/femasapi/{{ item }}"
    owner: trading
    group: trading
    mode: 0640
  with_items:
    - "master.conf"
    - "users.conf"
    - "symbols.conf"
    - "accounts.conf"
    - "md_user.conf"
    - "trader.conf"
    - "order_templates.conf"
    - "variables.conf"
    - "license.conf"
  tags:
  - roq-trading

- name: create scripts to start gateways
  become: true
  template:
    src: "templates/roq-gateway.sh"
    dest: "/trading/bin/roq-{{ item }}.sh"
    owner: trading
    group: trading
    mode: 0750
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: create run directories
  become: true
  file:
    path: "/trading/run/{{ item }}"
    state: directory
    owner: trading
    group: trading
    mode: 0750
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: create gateway stop service
  become: true
  template:
    src: "templates/roq-gateway-stop.service"
    dest: "/etc/systemd/system/roq-{{ item }}-stop.service"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: disable gateway stop service (will be triggered by the timer)
  become: true
  systemd:
    name: "roq-{{ item }}-stop.service"
    enabled: false
    daemon_reload: true
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: create gateway stop timer
  become: true
  template:
    src: "templates/roq-gateway-stop.timer"
    dest: "/etc/systemd/system/roq-{{ item }}-stop.timer"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: enable gateway stop timer
  become: true
  systemd:
    name: "roq-{{ item }}-stop.timer"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: create gateway service
  become: true
  template:
    src: "templates/roq-gateway.service"
    dest: "/etc/systemd/system/roq-{{ item }}.service"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: disable gateway service (will be triggered by the timer)
  become: true
  systemd:
    name: "roq-{{ item }}.service"
    enabled: false
    daemon_reload: true
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: create gateway launch timer
  become: true
  template:
    src: "templates/roq-gateway.timer"
    dest: "/etc/systemd/system/roq-{{ item }}.timer"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

- name: enable gateway launch timer
  become: true
  systemd:
    name: "roq-{{ item }}.timer"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - "{{ gateways }}"
  tags:
  - roq-trading

#################
### COLLECTOR ###
#################

- name: create script to start collector
  become: true
  template:
    src: "templates/roq-collector.sh"
    dest: "/trading/bin/roq-collector.sh"
    owner: trading
    group: trading
    mode: 0750
  tags:
  - roq-trading

- name: create run directory for collector
  become: true
  file:
    path: "/trading/run/collector"
    state: directory
    owner: trading
    group: trading
    mode: 0750
  tags:
  - roq-trading

- name: create collector stop service
  become: true
  template:
    src: "templates/roq-collector-stop.service"
    dest: "/etc/systemd/system/roq-collector-stop.service"
    owner: root
    group: root
    mode: 0644
  tags:
  - roq-trading

- name: disable collector stop service (will be triggered by the timer)
  become: true
  systemd:
    name: "roq-collector-stop.service"
    enabled: false
    daemon_reload: true
  tags:
  - roq-trading

- name: create collector stop timer
  become: true
  template:
    src: "templates/roq-collector-stop.timer"
    dest: "/etc/systemd/system/roq-collector-stop.timer"
    owner: root
    group: root
    mode: 0644
  tags:
  - roq-trading

- name: enable collector stop timer
  become: true
  systemd:
    name: "roq-collector-stop.timer"
    state: started
    enabled: true
    daemon_reload: true
  tags:
  - roq-trading

- name: create collector service
  become: true
  template:
    src: "templates/roq-collector.service"
    dest: "/etc/systemd/system/roq-collector.service"
    owner: root
    group: root
    mode: 0644
  tags:
  - roq-trading

- name: disable collector service (will be triggered by the timer)
  become: true
  systemd:
    name: "roq-collector.service"
    enabled: false
    daemon_reload: true
  tags:
  - roq-trading

- name: create collector launch timer
  become: true
  template:
    src: "templates/roq-collector.timer"
    dest: "/etc/systemd/system/roq-collector.timer"
    owner: root
    group: root
    mode: 0644
  tags:
  - roq-trading

- name: enable collector launch timer
  become: true
  systemd:
    name: "roq-collector.timer"
    state: started
    enabled: true
    daemon_reload: true
  tags:
  - roq-trading
