---

# https://medium.com/@frjalex/linux-kernel-high-performance-networking-how-to-2d35f5900974
# https://serverfault.com/questions/623780/low-latency-tcp-settings-on-ubuntu
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_MRG/2/html/Realtime_Tuning_Guide/index.html

- block:

  - name: update sysctl.conf (very aggressive settings)
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
    with_items:
    - { name: "net.core.rmem_max", value: "1342177280" }
    - { name: "net.core.wmem_max", value: "1342177280" }
    - { name: "net.ipv4.tcp_rmem", value: "163840 3495200 268754560" }
    - { name: "net.ipv4.tcp_wmem", value: "163840 3495200 268754560" }
    - { name: "net.ipv4.udp_rmem_min", value: "163840 3495200 268754560" }
    - { name: "net.ipv4.udp_wmem_min", value: "163840 3495200 268754560" }
    - { name: "net.ipv4.tcp_mem", value: "268754560 268754560 268754560" }
    - { name: "net.ipv4.udp_mem", value: "268754560 268754560 268754560" }
    - { name: "net.core.netdev_max_backlog", value: "300000" }
    tags:
    - tuning

  become: true
