---

- block:

  - name: add groups
    group:
      name: "{{ item }}"
      state: present
    with_items:
    - trading
    - algo
    tags:
    - infra

  - name: add users
    user:
      name: "{{ item }}"
      system: yes
      group: "{{ item }}"
    with_items:
    - trading
    - algo
    tags:
    - infra

  - name: create directories for trading
    file:
      path: "{{ item }}"
      state: directory
      owner: trading
      group: trading
      mode: 0750
    with_items:
    - /trading
    - /trading/config
    - /trading/bin
    - /trading/run
    - /trading/logs
    - /trading/infra
    - /trading/data
    tags:
    - infra

  - name: create directories for algo
    file:
      path: "{{ item }}"
      state: directory
      owner: algo
      group: algo
      mode: 0750
    with_items:
    - /algo
    - /algo/config
    - /algo/bin
    - /algo/logs
    tags:
    - infra

  become: true
