---
###############
### NETDATA ###
###############

- name: pull docker image
  become: true
  docker_image:
    name: "redis"
    http_timeout: 300
  tags:
  - redis

- name: create directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - "{{ redis_etc_dir }}"
  - "{{ redis_lib_dir }}"
  notify:
  - restart redis
  tags:
  - redis

- name: create config file
  become: true
  template:
    src: "templates/redis.conf"
    dest: "{{ redis_etc_dir }}/redis.conf"
    owner: root
    group: root
    mode: 0644
  register: redis_service
  notify:
  - restart redis
  tags:
  - redis

- name: create systemd service
  become: true
  template:
    src: "templates/redis.service"
    dest: "/etc/systemd/system/redis.service"
    owner: root
    group: root
    mode: 0644
  register: redis_service
  notify:
  - restart redis
  tags:
  - redis

- name: service -> systemctl daemon-reload
  become: true
  shell: systemctl daemon-reload
  when: redis_service.changed
  notify:
  - restart redis
  tags:
  - redis

- name: enable service
  become: true
  service:
    name: redis
    enabled: yes
  tags:
  - redis
