---

###############
### NETDATA ###
###############

- name: pull docker image
  become: true
  docker_image:
    name: "titpetric/netdata"
    http_timeout: 300
  tags:
  - netdata

- name: create systemd service
  become: true
  template:
    src: "templates/netdata.service"
    dest: "/etc/systemd/system/netdata.service"
    owner: root
    group: root
    mode: 0644
  register: netdata_service
  notify:
  - restart netdata
  tags:
  - netdata

- name: service -> systemctl daemon-reload
  become: true
  shell: systemctl daemon-reload
  when: netdata_service.changed
  notify:
  - restart netdata
  tags:
  - netdata

- name: enable service
  become: true
  service:
    name: netdata
    enabled: yes
  tags:
  - netdata
