---

##############
### ONLOAD ###
##############

- name: check driver
  shell: "lsmod | grep ^onload"
  register: onload_driver
  failed_when: onload_driver.rc > 1
  changed_when: onload_driver.rc == 1
  tags:
    - onload

- name: check if package already has been downloaded
  stat:
    path: "/opt/openonload-{{ onload_ver }}.tgz"
  register: onload_package
  tags:
    - onload

- name: download package
  when: not onload_package.stat.exists and onload_driver is changed
  become: true
  get_url:
    url: "http://www.openonload.org/download/openonload-{{ onload_ver }}.tgz"
    dest: "/opt"
    owner: root
    mode: 0644
    timeout: 300
  tags:
    - onload

- name: extract package
  when: onload_driver is changed
  become: true
  unarchive:
    remote_src: true
    src: "/opt/openonload-{{ onload_ver }}.tgz"
    dest: "/tmp"
  register: onload_source
  tags:
    - onload

- name: check uninstall manifest
  stat:
    path: "/usr/libexec/onload/uninstall_manifest"
  register: onload_uninstall
  tags:
    - onload

- name: uninstall old driver
  when: onload_uninstall.stat.exists and onload_source is changed
  become: true
  command: "/tmp/openonload-{{ onload_ver }}/scripts/onload_misc/onload_uninstall"
  tags:
    - onload

- name: install new driver
  when: onload_source is changed
  become: true
  command: "/tmp/openonload-{{ onload_ver }}/scripts/onload_install"
  tags:
    - onload

- name: reload driver
  when: onload_source is changed
  become: true
  command: "/tmp/openonload-{{ onload_ver }}/scripts/onload_tool reload"
  tags:
    - onload
