---

- name: pull docker images
  become: true
  docker_image:
    name: "prom/prometheus"
    http_timeout: 300
  with_items:
    - "prom/prometheus"
    - "prom/node-exporter"
  tags:
  - prometheus

##################
### PROMETHEUS ###
##################

- name: create config directory
  become: true
  file:
    path: "/etc/prometheus"
    state: directory
    owner: root
    group: root
    mode: 0755
  notify:
  - restart prometheus
  tags:
  - prometheus

- name: create config file
  become: true
  template:
    src: "templates/prometheus.yml"
    dest: "/etc/prometheus/prometheus.yml"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart prometheus
  tags:
  - prometheus

- name: create database directory
  become: true
  file:
    path: "/var/lib/prometheus"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0777
  notify:
  - restart prometheus
  tags:
  - prometheus

- name: create systemd service
  become: true
  template:
    src: "templates/prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"
    owner: root
    group: root
    mode: 0644
  register: prometheus_service
  notify:
  - restart prometheus
  tags:
  - prometheus

- name: service -> systemctl daemon-reload
  become: true
  shell: systemctl daemon-reload
  when: prometheus_service.changed
  notify:
  - restart prometheus
  tags:
  - prometheus

- name: enable service
  become: true
  service:
    name: prometheus
    enabled: yes
  tags:
  - prometheus

#####################
### NODE-EXPORTER ###
#####################

- name: create systemd service
  become: true
  template:
    src: "templates/node-exporter.service"
    dest: "/etc/systemd/system/node-exporter.service"
    owner: root
    group: root
    mode: 0644
  register: node_exporter_service
  notify:
  - restart node-exporter
  tags:
  - prometheus

- name: service -> systemctl daemon-reload
  become: true
  shell: systemctl daemon-reload
  when: node_exporter_service.changed
  notify:
  - restart node-exporter
  tags:
  - prometheus

- name: enable service
  become: true
  service:
    name: node-exporter
    enabled: yes
  tags:
  - prometheus
