---

#################
### MINICONDA ###
#################

- name: install miniconda3
  become: true
  get_url:
    url: "https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/{{ item }}"
    dest: "/opt"
    owner: root
    mode: 0755
  environment: "{{proxy_env | default({})}}"
  with_items:
  - "Miniconda3-latest-Linux-x86_64.sh"
  tags:
    - conda

- name: create miniconda3 symlink
  become: true
  file:
    src: "/opt/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
  - "Miniconda3-latest-Linux-x86_64.sh"
  tags:
  - conda

- name: create .condarc
  become: true
  template:
    src: "templates/condarc"
    dest: "/root/.condarc"
    owner: root
    mode: 0644
  tags:
  - conda
