---

###########
### PIP ###
###########

- name: install pip (debian)
  become: true
  apt:
    name: "{{ item }}"
  environment: "{{proxy_env | default({})}}"
  with_items:
    - python-setuptools
    - python-pip
  when: ansible_os_family == "Debian"
  tags:
  - python

- name: install pip (redhat)
  become: true
  yum:
    name: python-setuptools
  environment: "{{proxy_env | default({})}}"
  when: ansible_os_family == "RedHat"
  tags:
  - python

- name: easy install pip
  become: true
  easy_install:
    name: pip
    state: latest
  environment: "{{proxy_env | default({})}}"
  when: ansible_os_family == "RedHat"
  tags:
  - python
