global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

{% for gateway in gateways %}
  - job_name: 'quinclas-{{ gateway }}'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:{{ gateway_ports[gateway] }}']
{% endfor %}
